### ISSUE TITLE
SentenenceComplexityAnalyzer Chart is not showing data when window is full window mode

### ISSUE THREAD

**Issue by ghost** [NoxAG/NewNox-Application#60]
![chartbugbigwindow](https://user-images.githubusercontent.com/31410008/31816407-823f6216-b590-11e7-8896-333a117af499.PNG)
![chartbugsmallwindow](https://user-images.githubusercontent.com/31410008/31816408-825c444e-b590-11e7-815a-cd5121e88d63.PNG)

**Comment by ghost** [comment]
This bug is occurring when testing with "Praxisarbeit_PE_I_Pascal_Schröder_unsigned" but not when using another pdf file

**Comment by PascalSchroederDE** [comment]
Not to reproduce
