### ISSUE TITLE
SentenceComplexityAnalyzer Bug

### ISSUE THREAD

**Issue by PascalSchroederDE** [NoxAG/NewNox-Application#63]
Satz, der auf zwei Seiten aufgeteilt ist, wird zweite Hälfte (auf 2. Seite) nicht mit markiert.

**Comment by PascalSchroederDE** [comment]
(Evaluierung... PA Ende Seite 12+Anfang Seite 13)

**Comment by ghost** [comment]
Fixing this would take to much time
