### ISSUE TITLE
Differents in font size only between 10 and 14

### ISSUE THREAD

**Issue by PascalSchroederDE** [NoxAG/NewNox-Application#68]
Vorschlag 1: Nur ganze Paragraphen durch (eigene) reduceToContent (ähnliche) Methode mit Schriftarten 10-14 herausfiltern anstatt von Zeilen.

Vorschlag 2: In User Guide schreiben, dass nur minimalistische Unterschiede markiert werden, die evtl. nicht mit bloßem Auge sichtbar sind, weil andere leicht ersichtlich/auffallend oder bewusst gewollt wären.

**Comment by PascalSchroederDE** [comment]
@luciehopp Bitte schreibe in den User Guide, dass wir bei dem fontAnalyzer nur die Unterschiede markieren, die evtl. nicht mit dem Auge ersichtlich wären, da wir davon ausgehen, dass die Anderen schon ohnehin auffallen würden und wahrscheinlich auch gewollt sind.

**Comment by luciehopp** [comment]
done
